### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by codegauravg** [zaggino/brackets-git#1001]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (linux), Git 1.9.1 & Brackets-Git 0.14.24*

**Pushing to remote failed**

```
Error: error: failed to push some refs to 'https://codegauravg:***@github.com/codegauravg/Inkbrain-Website'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

```
call: git push --porcelain --progress Inkbrain-Website master
Error: error: failed to push some refs to 'https://codegauravg:gooday2diehard@github.com/codegauravg/Inkbrain-Website'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at Object.exports.toError (file:///home/codey/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/codey/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
you need to `pull` from remote first, read the hints

**Comment by codegauravg** [comment]
Its not working like that. I pulled it but again it shows the same error.

**Comment by zaggino** [comment]
you probably have an error pulling then, because this error message is coming directly from git, there's nothing it can be done here ... make git pull and make sure it worked, or pull with a rebase
