### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by sc-web** [zaggino/brackets-git#1004]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.24*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress origin development
```

```
call: git push --porcelain --progress origin development
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress origin development
    at timeoutPromise (file:///C:/Users/SC/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/SC/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git#features-and-limitations
