### ISSUE TITLE
Unexpected error in CLI handler - close all instances of Brackets and start again to reload

### ISSUE THREAD

**Issue by terehov** [zaggino/brackets-git#1009]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (mac) & Brackets-Git 0.14.24*

**Unexpected error in CLI handler - close all instances of Brackets and start again to reload**

```
TypeError: Cannot read property 'spawn' of undefined
```

```
TypeError: Cannot read property 'spawn' of undefined
    at file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:167:47
    at tryCatch1 (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2666:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/eugene/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by zaggino** [comment]
Seems like a memory leak, can you provide the list of all installed extensions?

**Comment by terehov** [comment]
Yep, sounds  reasonable since Brackets is getting slower and slower during the day and I have to restart it once every couple of hours. 

Here's the list: 

- Atom Light Theme: 1.0.5
- Beautify: 1.1.6
- Brackets Git 0.14.24
- Brackets SASS 2.0.1.-109
- Brackets TSLint 0.1.1
- Brackets TypeScript 0.2.0
- Code Folding 0.3.4
- Extract for Brackets (Preview) 0.7.0-1765-release
- JavaScript Globals 3.0.0
- QuickDocsJS 1.6.5
- Ternific 0.7.3
- Theseus for Brackets 0.4.19

Thanks!

**Comment by zaggino** [comment]
Ok, so does the above error happen immediately or after a time Brackets are opened?

**Comment by terehov** [comment]
This error (alert) happened for the first time, immediately after restarting Brackets. 
Usually it's just getting slower and slower – especially when switching files.

**Comment by zaggino** [comment]
Well if this happens all the time, you could start by disabling some of the extensions. If it's random, than I've no idea ... I've seen this error before when using some extensions which I know cause problems but you have none of those.
