### ISSUE TITLE
Git bug

### ISSUE THREAD

**Issue by Janee** [zaggino/brackets-git#1015]
Always I open Bracket on Windows 8.1 with a repo folder, display the next error: (Sorry for bad english)

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.4.msysgit.1 & Brackets-Git 0.14.24*

```
Error: fatal: Reference has invalid format: 'refs/remotes/origin/master
'
```

```
call: git branch --no-color
Error: fatal: Reference has invalid format: 'refs/remotes/origin/master
'
    at Object.exports.toError (file:///C:/Users/DianaJaneth/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/DianaJaneth/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Can you execute `git branch --no-color` in your repository and post the results here? Thanks
