### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by mpermana99** [zaggino/brackets-git#1031]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.26*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: C:\Program Files\Git\cmd\git.exe push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: C:\Program Files\Git\cmd\git.exe push --porcelain --progress origin master
    at timeoutPromise (file:///C:/Users/permana/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/permana/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1055: For some reason, my installation of git on windows doesn't seem to recognise the options --porcelain or --progress.
#1091: Committed 2 files, tried to push to bitbucket (I had internet connectivity) and it failed to push :/


Versions:

* Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.26
* Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27
* Brackets 1.3.0-16022 (mac), Git 2.3.5 & Brackets-Git 0.14.27
* Brackets 1.4.0-16380 (win), Git 1.8.1.msysgit.1 & Brackets-Git 0.14.28

Running with `Git 1.8.1.msysgit.1` manually, push worked:

```
$ git push --porcelain --progress origin master
Warning: Permanently added 'github.com,*.*.*.*' (RSA) to the list of known hosts.
Counting objects: 32, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (14/14), 1.53 KiB | 0 bytes/s, done.
Total 14 (delta 10), reused 0 (delta 0)
To git@github.com:*/*.git
        refs/heads/master:refs/heads/master     8edbc30..99826bf
Done
```

**Comment by iegik** [comment]
Maybe need to remove system errors and wornings from git push command?:
```
-- git push --porcelain --progress origin master
++ git push --porcelain --progress origin master 2> /dev/null
```
