### ISSUE TITLE
Switching branches failed.

### ISSUE THREAD

**Issue by TyMerrill767** [zaggino/brackets-git#1036]
Hello,

For some reason it won't let me switch branches because of some change to the .DS_Store file in my project folder, telling me to "stash or commit changes before switching branches" and aborting, even though I added .DS_Store to my .gitignore file. Is there any way around this?

--------------------------------

*Brackets 1.2.0-15697 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.26*

**Switching branches failed.**

```
Error: error: Your local changes to the following files would be overwritten by checkout:
	.DS_Store
Please, commit your changes or stash them before you can switch branches.
Aborting
```

```
call: git checkout skill_chart
Error: error: Your local changes to the following files would be overwritten by checkout:
	.DS_Store
Please, commit your changes or stash them before you can switch branches.
Aborting
    at Object.exports.toError (file:///Users/tmerrill/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/tmerrill/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Don't ever commit `.DS_Store` to git. You need to remove all `.DS_Store` files from your git repository:
```
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch
git commit -m '.DS_Store banished!'
```
http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository
