### ISSUE TITLE
Switching branches failed.

### ISSUE THREAD

**Issue by hamidabdulmalik** [zaggino/brackets-git#1037]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (linux), Git 2.4.0 & Brackets-Git 0.14.26*

**Switching branches failed.**

```
Error: error: Your local changes to the following files would be overwritten by checkout:
	app/views/jobs/index.html.erb
Please, commit your changes or stash them before you can switch branches.
Aborting
```

```
call: git checkout master
Error: error: Your local changes to the following files would be overwritten by checkout:
	app/views/jobs/index.html.erb
Please, commit your changes or stash them before you can switch branches.
Aborting
    at Object.exports.toError (file:///home/ida/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/ida/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Read your errors:
```
Error: error: Your local changes to the following files would be overwritten by checkout:
    app/views/jobs/index.html.erb
Please, commit your changes or stash them before you can switch branches.
Aborting
```
