### ISSUE TITLE
Remove scope failed

### ISSUE THREAD

**Issue by kadjei01** [zaggino/brackets-git#1040]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

Step 1 - Enable Git-FTP remotes
Step 2 - Create new Git-FTP remote
Step 3 - Remove new Git-FTP remove (using the "x" next to the newly created FTP: connection ) 
--------------------------------

*Brackets 1.3.0-16022 (mac), Git 1.9.5 (Apple Git-50.3) & Brackets-Git 0.14.26*

**Remove scope failed**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp remove-scope Live Server
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///Users/Username/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/Username/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git/blob/master/docs/GIT-FTP.md
