### ISSUE TITLE
Fetching remote information failed 

### ISSUE THREAD

**Issue by Willjobs94** [zaggino/brackets-git#1050]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (mac), Git 2.4.0 & Brackets-Git 0.14.27*

**Fetching remote information failed**

```
Error: fatal: I don't handle protocol 'git remote add origin https'
```

```
call: git fetch --progress Arduino
Error: fatal: I don't handle protocol 'git remote add origin https'
    at Object.exports.toError (file:///Users/Willjobs/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/Willjobs/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by Willjobs94** [comment]
I added the remote from the terminal, cause i wasn't able to add remote using the GUI
