### ISSUE TITLE
Init scope failed - FYI: im using Windows 7 - looking forward to updates to your extenstions for other OS

### ISSUE THREAD

**Issue by errinjohnson** [zaggino/brackets-git#1052]
I was just trying to delete the git-ftp and had gotten the following error below, tried init and received the same exact error.  

[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27*

**Init scope failed**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp init --scope codelouisville
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///C:/Users/sporttrac/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/sporttrac/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by errinjohnson** [comment]
It seems it be reversed on the call: "git ftp init", should be "git init ftp" ?

**Comment by zaggino** [comment]
Call is fine, you need to install git-ftp -> https://github.com/zaggino/brackets-git/blob/master/docs/GIT-FTP.md
