### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by GuiAlmeida** [zaggino/brackets-git#1068]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27*

**Refreshing gutter failed!**

```
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe status -u --porcelain -- php_src/z3/public/js/more.js
```

```
call: git status -u --porcelain -- php_src/z3/public/js/more.js
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe status -u --porcelain -- php_src/z3/public/js/more.js
    at timeoutPromise (file:///C:/Users/Guilherme/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/Guilherme/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:273:29
```

**Comment by DigitalLeaves** [comment]
Same problem here. Every minute.
