### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by eivanphils** [zaggino/brackets-git#1069]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (linux), Git 1.9.1 & Brackets-Git 0.14.27*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///home/phils/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///home/phils/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1031
