### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by Moter8** [zaggino/brackets-git#1091]
Committed 2 files, tried to push to bitbucket (I had internet connectivity) and it failed to push :/
--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.27*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///C:/Users/schaichhinten/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/schaichhinten/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1031
