### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by AvinashMudunuri** [zaggino/brackets-git#1093]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (mac), Git 2.3.5 & Brackets-Git 0.14.27*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: /usr/local/git/bin/git push --porcelain --progress origin R2.3_july
```

```
call: git push --porcelain --progress origin R2.3_july
Error: cmd-spawn-timeout: /usr/local/git/bin/git push --porcelain --progress origin R2.3_july
    at timeoutPromise (file:///Users/amudun/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///Users/amudun/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by iegik** [comment]
#1031
