### ISSUE TITLE
Not work on Brackets 1.4 

### ISSUE THREAD

**Issue by Daaru00** [zaggino/brackets-git#1115]
On startup brackets crash with this error

```javascript
[brackets-git] Error
    at Object.<anonymous> (file:///home/user/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) Utils.js:344
Possibly unhandled Error: Max connection attempts reached
    at Object.exports.toError (file:///home/user/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at Object.<anonymous> (file:///home/user/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:67:37)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28405)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as reject] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at Object.eval (/utils/NodeConnection.js:320:34)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28280) bluebird.js:458
Possibly unhandled Error
    at Object.<anonymous> (file:///home/user/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) 
```

**Comment by zaggino** [comment]
See #410 and #468

**Comment by zaggino** [comment]
Also https://github.com/zaggino/brackets-git/issues/1109
