### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by dnepro** [zaggino/brackets-git#1121]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.4.6 & Brackets-Git 0.14.27*

**Refreshing gutter failed!**

```
Error: cmd-spawn-timeout: /usr/local/bin/git status -u --porcelain -- Configuration/PackageStates.php
```

```
call: git status -u --porcelain -- Configuration/PackageStates.php
Error: cmd-spawn-timeout: /usr/local/bin/git status -u --porcelain -- Configuration/PackageStates.php
    at timeoutPromise (file:///Users/dnepro/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///Users/dnepro/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:273:29
```

**Comment by DigitalLeaves** [comment]
Why are these being closed?
