### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by mcissel** [zaggino/brackets-git#1130]
I can push to remote using the console, the mingw one that you provide, :)
I don't have "Windows Credential Store for Git" yet. I'm installing that now to see if it solves my issue.

--------------------------------

*Brackets 1.4.0-16380 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.28*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///C:/Users/Martin/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/Martin/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by mcissel** [comment]
yup! that fixes it for me. Just download [Windows Credential Store for Git](http://gitcredentialstore.codeplex.com/), like zaggino said to in the readme
