### ISSUE TITLE
Unexpected error in CLI handler - close all instances of Brackets and start again to reload

### ISSUE THREAD

**Issue by thaodt** [zaggino/brackets-git#1132]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (win) & Brackets-Git 0.14.28*

**Unexpected error in CLI handler - close all instances of Brackets and start again to reload**

```
TypeError: Cannot read property 'spawn' of undefined
```

```
TypeError: Cannot read property 'spawn' of undefined
    at file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:167:47
    at tryCatch1 (file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (file:///C:/Users/84036/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2666:14)
    at As

**Comment by bevinhex** [comment]
I got the same issue, I just installed brackets by
sudo npm -g install brackets
sudo brackets --port 99 --proj-dir ~/Desktop/workspace --supp-dir ~/Desktop/workspace/
opened localhost:99
installed brackets-git plugin
refreshed the page, got a popup saying "TypeError: Cannot read property 'spawn' of undefined"
