### ISSUE TITLE
Error Opening Bash/Terminal console

### ISSUE THREAD

**Issue by spietrek** [zaggino/brackets-git#1150]
I upgraded to the latest version. When attempting to open Bash/Terminal console, I receive the following error. I am using iTerm as my default.

"Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:523:609: execution error: Expected end of line but found class name. (-2741): osascript "/Users/stevepietrek/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/StevePietrek/Documents/Projects/hanes.faa/""

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.30*

```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:523:609: execution error: Expected end of line but found class name. (-2741): osascript "/Users/stevepietrek/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/StevePietrek/Documents/Projects/hanes.faa/"
```

```
Error: Error: /Users/stevepietrek/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:523:609: execution error: Expected end of line but found class name. (-2741): osascript "/Users/stevepietrek/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/StevePietrek/Documents/Projects/hanes.faa/"
    at file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:72:19
    at tryCatch1 (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_rejectPromises [as _rejectPromises] (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2658:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/StevePietrek/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by zaggino** [comment]
What's your iTerm version?
cc @macbookandrew

**Comment by spietrek** [comment]
2.1.1

**Comment by spietrek** [comment]
Should I upgrade to 2.9 beta?

**Comment by macbookandrew** [comment]
Could you try changing line 20 from this
`if app_version > 2.1 then`
to this:
`if app_version > 2.2 then`
and let us know if it works?

**Comment by macbookandrew** [comment]
It’s up to you whether to upgrade to iTerm 2.9 or not—this script is supposed to check the version number and use new code for the beta if needed. If you don’t mind, could you test the changes above with iTerm 2.1.1?

**Comment by spietrek** [comment]
Sure thing. Which file should I make the change?

**Comment by macbookandrew** [comment]
Sorry…here’s the path to the file that needs changed:

/Users/stevepietrek/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa

**Comment by spietrek** [comment]
That worked! Thanks Andrew.

**Comment by macbookandrew** [comment]
:+1: Thanks for your help!
