### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by FezVrasta** [zaggino/brackets-git#1153]
Clicking on the terminal icon after the today update.

--------------------------------

*Brackets 1.4.0-0 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.31*

```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/federicozivolo/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/federicozivolo/Progetti/sysdigcloud/frontend/"
```

```
Error: Error: /Users/federicozivolo/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/federicozivolo/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/federicozivolo/Progetti/sysdigcloud/frontend/"
    at file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:72:19
    at tryCatch1 (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_rejectPromises [as _rejectPromises] (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2658:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by zaggino** [comment]
cc @macbookandrew

**Comment by macbookandrew** [comment]
Do you have iTerm installed and if so, what version?

**Comment by FezVrasta** [comment]
I use iterm2

**Comment by macbookandrew** [comment]
Can you go to the app, Get Info, and let me know what the specific version number is?

**Comment by FezVrasta** [comment]
It's 2.1.1, the latest stable

**Comment by macbookandrew** [comment]
There’s a newer version of Brackets Git; could you update and test again please?

**Comment by FezVrasta** [comment]
Still the same error :(

**Comment by AscaL** [comment]
Same error here, also have the `2.1.1` version of iTerm2

*Brackets 1.4.0-16380 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.32*



```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/***/Development/snappin-signage-server/"
```

```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/***/Development/snappin-signage-server/"
    at file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:72:19
    at tryCatch1 (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_rejectPromises [as _rejectPromises] (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2658:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by macbookandrew** [comment]
Can you try changing the “Custom terminal command” filed in brackets-git settings from this:
`/Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa`

to this:
`/Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/iterm.osa`

and see if it works? If not, please supply the error message.

**Comment by FezVrasta** [comment]
it works

**Comment by macbookandrew** [comment]
Ok…that’s just odd, because it’s running exactly the same script that `terminal.osa` was calling for.

**Comment by AscaL** [comment]
yup also works for me :)
