### ISSUE TITLE
Failed to connect to nodejs error

### ISSUE THREAD

**Issue by ckoo7** [zaggino/brackets-git#1157]
`Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at _handlerOn (file:///home/chandra/.config/Brackets/extensions/user/brackets-quick-search/main.js:195:9)
    at file:///home/chandra/.config/Brackets/extensions/user/brackets-quick-search/main.js:223:21
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1107:29)
    at Pane.trigger (/utils/EventDispatcher.js:222:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:729:14)
    at Pane.showView (/view/Pane.js:1011:14)
    at _showEditor (/editor/EditorManager.js:562:14)
    at Object.openDocument (/editor/EditorManager.js:634:13)
    at _edit (/view/MainViewManager.js:1208:23) /utils/DeprecationWarning.js:90
Worker: Error thrown in tern_worker:Object #<Object> has no method 'SpreadElement'
TypeError: Object #<Object> has no method 'SpreadElement'
    at infer (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1100:39)
    at Object.walk.make.Expression (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/tern/lib/infer.js:1105:7)
    at c (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
    at Object.base.ExpressionStatement (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:176:5)
    at c (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:163:39)
    at c (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
    at Object.base.Program.base.BlockStatement (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:171:7)
    at c (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:163:39)
    at c (file:///opt/brackets/www/extensions/default/JavaScriptCodeHints/thirdparty/acorn/util/walk.js:60:37) ScopeManager.js:1073
[CodeInspection] Provider ESLint (async) failed: Max connection attempts reached /language/CodeInspection.js:277
[brackets-git] Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) Utils.js:349
[brackets-git] Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) Utils.js:349
[brackets-git] Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) Utils.js:349
[brackets-git] Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) Utils.js:349
Possibly unhandled Error: Max connection attempts reached
    at Object.exports.toError (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:67:37)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28405)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as reject] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at Object.eval (/utils/NodeConnection.js:320:34)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28280)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as reject] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at WebSocket.ws.onclose (/utils/NodeConnection.js:99:30) bluebird.js:458
Possibly unhandled Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) bluebird.js:458
Possibly unhandled Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) bluebird.js:458
Possibly unhandled Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) bluebird.js:458
Possibly unhandled Error
    at Object.<anonymous> (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29)`

above its my brackets console. Hope It can be solved

**Comment by ckoo7** [comment]
![screenshot from 2015-08-26 12-55-38](https://cloud.githubusercontent.com/assets/8359963/9487699/cba5d008-4bf1-11e5-87cd-03fdadedf8a5.png)


seeing this error when trying to reload nodejs

**Comment by ckoo7** [comment]
![screenshot from 2015-08-26 12-58-25](https://cloud.githubusercontent.com/assets/8359963/9487741/2bd6b8ca-4bf2-11e5-89c9-c0130fb01dbd.png)

**Comment by zaggino** [comment]
See:
#1149
#1058
#468
#410

**Comment by ckoo7** [comment]
I can not see any solutions there :( Sorry!! I am new to this. Thanx for the help

**Comment by zaggino** [comment]
Try disabling all the extensions except for brackets-git, see if it works. If yes, your problem is caused by another extension...

**Comment by ckoo7** [comment]
Yes, I disabled every extension and reloaded my brackets, still I am seeing that error :(
