### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by RIAEvangelist** [zaggino/brackets-git#1159]
Just saved the file.

Also happens any time when opening folder. And any time when saving the file.

--------------------------------

*Brackets 1.4.0-16380 (linux), Git 1.9.1 & Brackets-Git 0.14.32*

**Refreshing gutter failed!**

```
Error: fatal: unable to read tree 291429c0799792e7d871e1d4ba7beba2bc18f50e
```

```
call: git status -u --porcelain -- README.md
Error: fatal: unable to read tree 291429c0799792e7d871e1d4ba7beba2bc18f50e
    at Object.exports.toError (file:///home/bmiller/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/bmiller/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
Seems like a corrupted Git repository.
