### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by fauzie** [zaggino/brackets-git#1160]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.32*

**Refreshing gutter failed!**

```
Error: error: bad index file sha1 signature
fatal: index file corrupt
```

```
call: git status -u --porcelain -- template-parts/form-job_search_alt.php
Error: error: bad index file sha1 signature
fatal: index file corrupt
    at Object.exports.toError (file:***/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:***/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:***/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:***/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
https://www.google.com.au/search?q=index+file+corrupt
