### ISSUE TITLE
Creating new branch failed

### ISSUE THREAD

**Issue by Tibaus** [zaggino/brackets-git#1162]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (linux), Git 1.9.1 & Brackets-Git 0.14.32*

**Creating new branch failed**

```
Error: fatal: A branch named 'modificandojs' already exists.
```

```
call: git checkout -b modificandojs modificandojs
Error: fatal: A branch named 'modificandojs' already exists.
    at Object.exports.toError (file:///home/tsalgado/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/tsalgado/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
`A branch named 'modificandojs' already exists.`

**Comment by zaggino** [comment]
Note to self, make sure `A branch named 'modificandojs' already exists.` is properly parsed out of git and shown to user as user error.
