### ISSUE TITLE
brackets-git is broken

### ISSUE THREAD

**Issue by ShinDarth** [zaggino/brackets-git#1171]
On a fresh install of Brackets under Ubuntu 14.04.3 the plugin brackets-git is broken. I got no errors but the plugin buttons simply don't work, nothing happens.

I've tried the debug mode and the plugin doesn't work at all, I mean clicking in the icon of the plugin (that should open the bottom window) nothing happens too.

**Comment by zaggino** [comment]
Does other special Brackets features work for you? Live preview for example?

**Comment by ShinDarth** [comment]
Yes it does

**Comment by zaggino** [comment]
What's the color of the icon? Does it have any message at all?

**Comment by ShinDarth** [comment]
http://s12.postimg.org/z6x6jcli5/photo_2015_09_08_23_27_53.jpg

**Comment by zaggino** [comment]
I don't see any problems on that screenshot. Seems like the Git was find successfully, otherwise the bottom panel wouldn't open.

**Comment by ShinDarth** [comment]
Yes but everything else is broken, also sometimes even the bottom panel window doesn't open

**Comment by zaggino** [comment]
You'd have to provide some specific errors. You can try installing `brackets-file-tree-exclude` extension, if you have large `node_modules` folder in your project, it improves performance and responsivity a lot.

**Comment by ShinDarth** [comment]
@zaggino  how can I provide errors? I don't get any errors, just the buttons that worked before now stopped to work misteriously.. I tried to erase everything by formatting my computer and installing a fresh Ubuntu 14.04 but I got the same problem

**Comment by zaggino** [comment]
Debug > Show developer tools > Console - by default all errors appear here

**Comment by ShinDarth** [comment]
http://i.imgur.com/b0VUjWa.png

**Comment by zaggino** [comment]
Sorry, I'm out of ideas. Extension runs fine in my Ubuntu 14 VM and there isn't much I can do without being able to replicate your problem.

**Comment by ShinDarth** [comment]
@zaggino I see, anyway thanks for your time and thanks a lot for this awesome brackets extension :)

**Comment by ShinDarth** [comment]
Download the React DevTools for a better development experience: http://fb.me/react-devtools /thirdparty/react.js:4486
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24) /utils/DeprecationWarning.js:90
NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73300:9)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Registering for deprecated event 'workingSetAdd'. Instead, use MainViewManager.workingSetAdd. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73300:28)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:20:21
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:874:51)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///opt/brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///opt/brackets/www/thirdparty/requirejs/require.js:1163:17)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:925:30)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73301:9)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Registering for deprecated event 'workingSetAddList'. Instead, use MainViewManager.workingSetAddList. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73301:28)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:20:21
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:874:51)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///opt/brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///opt/brackets/www/thirdparty/requirejs/require.js:1163:17)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:925:30)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73302:9)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Registering for deprecated event 'workingSetRemove'. Instead, use MainViewManager.workingSetRemove. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73302:28)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:20:21
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:874:51)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///opt/brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///opt/brackets/www/thirdparty/requirejs/require.js:1163:17)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:925:30)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73303:9)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Registering for deprecated event 'workingSetRemoveList'. Instead, use MainViewManager.workingSetRemoveList. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73303:28)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:20:21
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:874:51)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///opt/brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///opt/brackets/www/thirdparty/requirejs/require.js:1163:17)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:925:30)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73305:9)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Use MainViewManager.getWorkingSet() instead of DocumentManager.getWorkingSet()
    at Object.getWorkingSet (/document/DocumentManager.js:160:28)
    at new WorkingSet (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73307:39)
    at initServices (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72502:18)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72478:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72480:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at init (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:72481:5)
    at file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/main.js:22:21
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.appReady (/utils/AppInit.js:141:9) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:474:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at WorkingSet.setActiveEditor (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73384:13)
    at WorkingSet.activeEditorChangeHandler (file:///home/shin/.config/Brackets/extensions/user/fdecampredon.brackets-typescript/bin/main.js:73298:19)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1107:29)
    at Pane.trigger (/utils/EventDispatcher.js:222:40)
    at Pane._notifyCurrentViewChange (/view/Pane.js:729:14)
    at Pane.showView (/view/Pane.js:1011:14)
    at _showEditor (/editor/EditorManager.js:562:14)
    at Object.openDocument (/editor/EditorManager.js:634:13)
    at _edit (/view/MainViewManager.js:1208:23)
    at Object.eval (/view/MainViewManager.js:1298:21)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as resolve] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at Object.eval (/document/DocumentManager.js:379:32)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith [as resolveWith] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at Object.e.(anonymous function) [as resolve] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28704)
    at eval (/file/FileUtils.js:83:24)
    at File.eval (/filesystem/File.js:125:13)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:378:25) /utils/DeprecationWarning.js:90
Max connection attempts reached, trying again. Utils.js:349
6
Max connection attempts reached, trying again.

**Comment by ShinDarth** [comment]
@zaggino I hope that log helps, your tool is so useful that I'm suffering without it :D

**Comment by zaggino** [comment]
There's been much written about `Max connection attempts reached` and it's not a problem of `brackets-git` ... see #410 #468 or with search:

https://github.com/zaggino/brackets-git/search?q=%22Max+connection+attempts+reached%22&type=Issues&utf8=%E2%9C%93

Some people solved this problem but I don't believe there's one solution that would fit all.
