### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by saenzramiro** [zaggino/brackets-git#1180]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.32*

**Refreshing gutter failed!**

```
Error: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


```

```
call: git status -u --porcelain -- app/app/ux/FieldReorder.js
Error: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


    at Object.exports.toError (file:///Users/saenzramiro/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/saenzramiro/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
Solution here: https://github.com/zaggino/brackets-git/issues/1191
