### ISSUE TITLE
Pulling from remote failed

### ISSUE THREAD

**Issue by gmaggio** [zaggino/brackets-git#1188]
I'm not really well versed handling things like this. I tried following the instructions under **"Working with SSH repositories"** but it doesn't seem to do anything. Any idea how I could solve this? Cheers.

--------------------------------

*Brackets 1.4.0-16380 (win), Git 2.5.0.windows.1 & Brackets-Git 0.14.32*

**Pulling from remote failed**

```
Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

```
call: git fetch --progress origin
Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at Object.exports.toError (file:///C:/Users/Aldi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/Aldi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
No idea, I don't work with SSH repositories.

**Comment by alignedleft** [comment]
I get the same issue on a Mac, after setting up and configuring my SSH --> Github connection manually, only before seeing the error, I am prompted to enter the SSH key passphrase. (I can push to Github just fine manually from the terminal without entering a passphrase.)

**Comment by zaggino** [comment]
Try turning on the debug mode in brackets-git settings and see what're the commands executed in brackets console, that might give you an idea what might be wrong.

**Comment by alignedleft** [comment]
Thanks! I made some SSH key changes and restarted Brackets. It's working now (so I'll never know what debug errors popped up). Thanks for this great tool!

**Comment by drimlike** [comment]
@alignedleft what do you mean by "I made some SSH key changes"? Same issue here on Windows. That would be great to know more about your magic trick! :)

**Comment by alignedleft** [comment]
Ah, there was no magic. I think I generated new SSH keys and/or made sure Github was aware of my new key, then restarted. I've forgotten the details, sorry! It seemed I needed to reboot before Brackets noticed the change.

**Comment by drimlike** [comment]
@zaggino do you have any advice to solve that problem? Doing it by opening the Git Bash terminal using the button from the extension works, but as soon as we push with the Git Push from the extension it doesn't work. Can you confirm that the extension uses the Windows command prompt to execute Git?

**Comment by drimlike** [comment]
Thanks for your feedback @alignedleft ;)

**Comment by zaggino** [comment]
Yes, the extension uses default command prompt on the given OS. I don't use SSH for Git so can't help here. You can turn on the debug mode in settings to get in and outs from command prompt in the brackets console.

**Comment by manthano** [comment]
I've only been able to get Brackets-git to work with SSH repositories by using my default id_dsa and id_rsa identities without passphrases. If I try to configure a unique identity for a server even though I have the identity added to my login session (ssh-add) and it works to git push, pull, etc from the terminal, it fails with the error above when using the buttons in Brackets-git. 

My guess is that Bracket-git uses its own session that doesn't have access to the current ssh-agent.

**Comment by alwinmarkcf** [comment]
@manthano @zaggino I can confirm, that it is not working when you protect your ssh key with a password (what you should btw). So using the terminal everything works fine. Using HTTPs everything works, but using ssh key which is password protected does not work but is the recommended and most secure method.
