### ISSUE TITLE
Remote creation failed

### ISSUE THREAD

**Issue by xgretsch** [zaggino/brackets-git#1189]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]
I have a remote Linux server whose ssh lives on port 2020. I have therefore set the following in my ~/.ssh/config:
Host btk_git_host
HostName example.com
Port 2020
User david

On the server, in /var/git/mbtk, I have done a:
git init --shared --bare

I have then tried to set this up as a new remote in brackets (inside Intel XDK) by specifying the following as the name of the new remote:
btk_git_host:/var/git/mbtk

I was asked the "Create new remote" dialog a second time, and then received this error.

What I don't understand is that this is my second project. It worked fine on the first one.

--------------------------------

*Brackets 1.4.0-0 (mac), Git 2.3.8 (Apple Git-58) & Brackets-Git 0.14.28*

**Remote creation failed**

```
Error: fatal: 'btk_git_host:/var/git/mbtk' is not a valid remote name
```

```
call: git remote add btk_git_host:/var/git/mbtk btk_git_host:/var/git/mbtk
Error: fatal: 'btk_git_host:/var/git/mbtk' is not a valid remote name
    at Object.exports.toError (file:///Users/david/Library/Application%20Support/XDK/editor/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/david/Library/Application%20Support/XDK/editor/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/brackets/b/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Intel%20XDK.app/Contents/Resources/app.nw/brackets/b/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by xgretsch** [comment]
Just discovered that everything is now OK after a reboot, which I think may have upgraded this plugin.
