### ISSUE TITLE
Pulling from remote failed

### ISSUE THREAD

**Issue by sensuigit** [zaggino/brackets-git#1201]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.32*

**Pulling from remote failed**

```
Error:       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x4D0000, State 0x10000
D:\Program Files (x86)\Git\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

```
call: git fetch --progress origin
Error:       0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x4D0000, State 0x10000
D:\Program Files (x86)\Git\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at Object.exports.toError (file:///C:/Users/sensui/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/sensui/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///D:/Program%20F

**Comment by zaggino** [comment]
google `Couldn't reserve space for cygwin's heap`
