### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by sensuigit** [zaggino/brackets-git#1202]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.32*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: D:\Program Files (x86)\Git\bin\git.exe push --porcelain --progress --set-upstream origin dev
```

```
call: git push --porcelain --progress --set-upstream origin dev
Error: cmd-spawn-timeout: D:\Program Files (x86)\Git\bin\git.exe push --porcelain --progress --set-upstream origin dev
    at timeoutPromise (file:///C:/Users/sensui/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:228:27)
    at file:///C:/Users/sensui/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:271:33
```

**Comment by sensuigit** [comment]
good job thanks  but have a bug

**Comment by sensuigit** [comment]
how fix?

**Comment by zaggino** [comment]
see README for pwd protected repositories
