### ISSUE TITLE
Failed push to Git-FTP remote.

### ISSUE THREAD

**Issue by macbookandrew** [zaggino/brackets-git#1209]
1. Upgrade to OS X El Capitan
2. Try to push to an existing git-ftp server

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.6.1 & Brackets-Git 0.14.32*

**Failed push to Git-FTP remote.**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp push --scope production
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///Users/andrew/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/andrew/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by macbookandrew** [comment]
I have “Path to Git executable” set to `/usr/local/bin/git`, where both `git` and `git-ftp` reside. However, I’m still getting the error above when trying to push to a server using Git-FTP.

Here’s output from my Terminal detailing the `git` and `git-ftp` installations:
```
$ whereis git
/usr/bin/git
$ /usr/bin/git --version
git version 2.3.8 (Apple Git-58)
$ which git
/usr/local/bin/git
$ /usr/local/bin/git --version
git version 2.6.1
$ which git-ftp
/usr/local/bin/git-ftp
$ /usr/local/bin/git-ftp --version
git-ftp version 1.0.2
```

The Brackets console lists the correct `git` executable specified in brackets-git preferences, but is still throwing the error:
![screen shot 2015-10-14 at 1 59 59 pm](https://cloud.githubusercontent.com/assets/784333/10493067/2652e732-727d-11e5-9084-5ff66130f7c5.png)

If I copy the command from the Brackets console and paste into Terminal, it works just fine:
```
$ /usr/local/bin/git-ftp push --scope production
There are 1 files to sync:
[1 of 1] Buffered for upload 'functions.php'.
Uploading ...
Last deployment changed to 85452f4ef8d8834a64df0a48df95f9303e704242.
```

@FezVrasta Any thoughts? I know I could disable SIP and move `git-ftp` into `/usr/bin/` and that might fix it, but this should be working just fine as well.

**Comment by VitaliyAT** [comment]
it's still a problem (Win 10, Brakets 1.7)
![screenshot 27](https://cloud.githubusercontent.com/assets/1639608/17243949/bfb6f89c-5598-11e6-8cee-2170216df248.jpg)
