### ISSUE TITLE
Pulling from remote failed

### ISSUE THREAD

**Issue by MohammadShawon** [zaggino/brackets-git#1228]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.5.0-16538 (win), Git 2.5.0.windows.1 & Brackets-Git 0.14.32*

**Pulling from remote failed**

```
Error: merge: origin/effc771 - not something we can merge
```

```
call: git merge origin/effc771
Error: merge: origin/effc771 - not something we can merge
    at Object.exports.toError (file:///C:/Users/mohammad/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/mohammad/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by vinukumar-vs** [comment]
![image](https://cloud.githubusercontent.com/assets/4496096/11420822/af325d6c-9456-11e5-97e7-5b095bb5177f.png)

Facing same problem..
Started using first time. Git fetch origin hangs Bracket every time... ;(
