### ISSUE TITLE
Everytime I click Terminal I get this error

### ISSUE THREAD

**Issue by laedri** [zaggino/brackets-git#1229]
Title says all.

I have iTerm but it's not default Terminal. iTerm firing without issue, but an error from Brackets pops up.

--------------------------------

*Brackets 1.5.0-16538 (mac), Git 2.5.1 & Brackets-Git 0.14.32*

```
Error: Error: /Users/*****/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/*****/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/*****/Desktop/*****/*****"
```

```
Error: Error: /Users/*****/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:524:610: execution error: Expected end of line but found class name. (-2741): osascript "/Users/*****/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/*****/Desktop/*****/*****"
    at file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:72:19
    at tryCatch1 (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_rejectPromises [as _rejectPromises] (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2658:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/*****/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by macbookandrew** [comment]
What version of iTerm are you using?
