### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by tylerrollins** [zaggino/brackets-git#1236]
[Simply opened a folder, that has worked several times in the past. All files / folder works on atom & sublime.] [I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.5.0-16538 (mac), Git 2.4.9 (Apple Git-60) & Brackets-Git 0.14.32*

**Refreshing gutter failed!**

```
Error: error: bad index file sha1 signature
fatal: index file corrupt
```

```
call: git status -u --porcelain -- .gitignore
Error: error: bad index file sha1 signature
fatal: index file corrupt
    at Object.exports.toError (file:///Users/tylerrollins/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/tylerrollins/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:556:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34)
```

**Comment by zaggino** [comment]
`index file corrupt` is a git message, only thing I can recommend is googling for it
