### ISSUE TITLE
Error: fatal: bad revision

### ISSUE THREAD

**Issue by ficristo** [zaggino/brackets-git#1308]
After startup of Brackets I've the following error. Note that I simply checkout my branch.
```js
ErrorNotification.js:125 [brackets-git] call: git rev-list --left-right --count bracketron/fix-folders-tree...@{0} --
Error: fatal: bad revision 'bracketron/fix-folders-tree...@{0}'
    at Object.exports.toError (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:157:19)
    at NodeConnection.<anonymous> (file:///C:/Users/<username>/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/thirdparty/jquery-2.1.3.min.js:2:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/thirdparty/jquery-2.1.3.min.js:2:27724)
    at NodeConnection._receive (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/NodeConnection.js:498:34)
```

I see `bracketron` in the error. I don't know if it is beacuse I've three remotes.
```shell
$ git remote -v
bracketron      https://github.com/zaggino/brackets-electron (fetch)
bracketron      https://github.com/zaggino/brackets-electron (push)
origin  https://github.com/ficristo/brackets.git (fetch)
origin  https://github.com/ficristo/brackets.git (push)
upstream        https://github.com/adobe/brackets.git (fetch)
upstream        https://github.com/adobe/brackets.git (push)
```

Possibly related to https://github.com/zaggino/brackets-git/issues/1272 and https://github.com/zaggino/brackets-git/issues/1299.

**Comment by ficristo** [comment]
Changing the remote through the GUI fixed it.
But I have a similar problem when I test some PR:
```js
call: git rev-list --left-right --count origin/pull-12041...@{0} --
Error: fatal: bad revision 'origin/pull-12041...@{0}'
```

**Comment by iegik** [comment]
```
[brackets-git] call: git rev-list --left-right --count origin/issue_#184...@{0} --
Error: fatal: bad revision 'origin/issue_#184...@{0}'
    at Object.exports.toError (file://~/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:158:19)
    at NodeConnection.<anonymous> (file://~/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:19:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:498:34) Utils.js:350
```
