### ISSUE TITLE
Unable to get initial commit details

### ISSUE THREAD

**Issue by mateoguzman** [zaggino/brackets-git#1311]
If you are in the commit history view and you click on your initial commit, you get the following error:

![capture](https://cloud.githubusercontent.com/assets/4228725/17781361/6ad50f14-6545-11e6-9bfc-c5bf0929c1cc.PNG)

This does not happens in the subsequents commits. 
I have researched a little bit and found that the reason of this is because the initial commit is not correctly flagged as initial commit so the git command is not the correct one. 

This only happens when the list of commits is short and there is no scroll bars in the history view.

Steps to reproduce: 
1. Open a new foler in Brackets
2. Open the Brackets Git extension
3. Init
4. Select a file and commit
5. Click on Show History
6. Click on the commit and you will get the error

I tested a fix flagging the initial commit on the renderHistory() function in src/History.js
Would you accept a pull-request for this?

Thank you 

Console output:
`Utils.js:349 [brackets-git] call: git diff --no-ext-diff --name-only dc9271ea9b44a1bd7f8b2b70d0d2213fe97089f6^..dc9271ea9b44a1bd7f8b2b70d0d2213fe97089f6 --
Error: fatal: bad revision 'dc9271ea9b44a1bd7f8b2b70d0d2213fe97089f6^..dc9271ea9b44a1bd7f8b2b70d0d2213fe97089f6'
    at Object.exports.toError (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:157:19)
    at NodeConnection.<anonymous> (file:///C:/Users/mguzman/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/thirdparty/jquery-2.1.3.min.js:2:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/thirdparty/jquery-2.1.3.min.js:2:27724)
    at NodeConnection._receive (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/NodeConnection.js:498:34)`

**Comment by zaggino** [comment]
@mateoguzman 
Brackets Git version 0.16.6 should contain your fix.

**Comment by mateoguzman** [comment]
Thanks @zaggino, I installed Brackets Git version 0.16.6 and it is fixed!
