### ISSUE TITLE
Not able to connect to git repo due to failure accessing git 'credential-osxkeychain'

### ISSUE THREAD

**Issue by zd-project** [zaggino/brackets-git#1334]
I was not able to pull/push to my github repository even the first time after installing brackets-git. I replicate the entire process in terminal but there wasn't any issue, suggesting it's something wrong with brackets-git.

My repo is private and I'm using Homebrew git

Console output
`[brackets-git] Event invoked: handle.push (1 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git rev-parse --abbrev-ref --symbolic-full-name @{u}
Utils.js:355 [brackets-git] cmd-spawn-out (19ms;ID=20): "origin/master"
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git config remote.origin.url
Utils.js:355 [brackets-git] cmd-spawn-out (10ms;ID=21): "https://github.com/USER/SOME.git"
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git branch --no-color -a
Utils.js:355 [brackets-git] cmd-spawn-out (13ms;ID=22): "* master
  remotes/origin/master"
Utils.js:355 [brackets-git] cmd-spawn-watch: /Users/***/DIR/ -> /usr/local/bin/git push --porcelain --progress origin master
Utils.js:355 [brackets-git] cmd-spawn-fail (348ms;ID=23): "git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured"
Utils.js:350 [brackets-git] call: git push --porcelain --progress origin master
Error: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
    at Object.exports.toError (file:///Users/***/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:158:19)
    at NodeConnection.<anonymous> (file:///Users/huzd/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:493:34)consoleLog @ Utils.js:350exports.logError @ ErrorHandler.js:90exports.showError @ ErrorHandler.js:98(anonymous function) @ Remotes.js:238tryCatch1 @ bluebird.js:4988Promise$_callHandler @ bluebird.js:2333Promise$_settlePromiseFromHandler @ bluebird.js:2349Promise$_settlePromiseAt @ bluebird.js:2521Promise$_rejectPromises @ bluebird.js:2658Async$_consumeFunctionBuffer @ bluebird.js:157Async$consumeFunctionBuffer @ bluebird.js:120Promise$_Scheduler @ bluebird.js:4260
Utils.js:350 [brackets-git] Event invoked: git.refresh.all (1 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git rev-parse --show-toplevel
2bluebird.js:458 Possibly unhandled call: git push --porcelain --progress origin master
Error: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
    at Object.exports.toError (file:///Users/huzd/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:158:19)
    at NodeConnection.<anonymous> (file:///Users/huzd/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:185:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:19:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:493:34)CapturedTrace$PossiblyUnhandledRejection @ bluebird.js:458Promise$_notifyUnhandledRejection @ bluebird.js:2691tryCatch1 @ bluebird.js:4988Async$_consumeLateBuffer @ bluebird.js:169Async$_consumeFunctionBuffer @ bluebird.js:160Async$consumeFunctionBuffer @ bluebird.js:120Promise$_Scheduler @ bluebird.js:4260
Utils.js:355 [brackets-git] cmd-spawn-out (13ms;ID=24): "/Users/***/DIR"
Utils.js:355 [brackets-git] Checking path for .git: /Users/***/DIR
Utils.js:355 [brackets-git] Found .git in path: /Users/***/DIR
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git branch --no-color
Utils.js:355 [brackets-git] cmd-spawn-out (24ms;ID=25): "* master"
Utils.js:350 [brackets-git] Event invoked: rebase.merge.mode - false, false (1 listeners)
Utils.js:350 [brackets-git] Event invoked: git.enabled (7 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git config user.name
Utils.js:355 [brackets-git] cmd-spawn-out (27ms;ID=26): "MY_NAME"
Utils.js:350 [brackets-git] Event invoked: git.username.changed - MY_NAME (1 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git config user.email
Utils.js:355 [brackets-git] cmd-spawn-out (16ms;ID=27): "MY_EMAIL"
Utils.js:350 [brackets-git] Event invoked: git.email.changed - MY_EMAIL (1 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git config gerrit.pushref
Utils.js:355 [brackets-git] cmd-spawn-out (16ms;ID=28)
Utils.js:350 [brackets-git] Event invoked: gerrit.push.ref.toggled - false (1 listeners)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git remote -v
Utils.js:355 [brackets-git] cmd-spawn-out (17ms;ID=29): "origin	https://github.com/USER/SOME.git (fetch)
origin	https://github.com/USER/SOME.git (push)"
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git status -u --porcelain
Utils.js:355 [brackets-git] cmd-spawn-out (31ms;ID=30)
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git branch --no-color
Utils.js:350 [brackets-git] Event invoked: git.status.results (3 listeners)
Utils.js:355 [brackets-git] cmd-spawn-out (20ms;ID=31): "* master"
Utils.js:355 [brackets-git] cmd-spawn: /Users/***/DIR/ -> /usr/local/bin/git rev-list --left-right --count origin/master...@{0} --
Utils.js:355 [brackets-git] cmd-spawn-out (27ms;ID=32): "0	0"`

**Comment by ttyson99** [comment]
After upgrading to High Sierra, this is happening to me as well.  My repo is also private on Github and I'm also using homebrew git.  Identical error message:
Error: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured

**Comment by Kaes3kuch3n** [comment]
Same here:
`Error: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
error: Could not fetch github`

**Comment by ttyson99** [comment]
I solved this by simply putting my github credentials in the username and password fields on the plugin

**Comment by Kaes3kuch3n** [comment]
I can't find any password field on the plugin. Where did you enter it exactly? @ttyson99

**Comment by Kaes3kuch3n** [comment]
I forgot to mention that I have this problem with fetching. Pushing and pulling works without any problems, there are username and password fields where I can enter my data and execute it. But there are no fields for username and password when I try to execute a fetch operation and therefore I get the error message:
`Error: git: 'credential-osxkeychain' is not a git command. See 'git --help'.
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': Device not configured
error: Could not fetch origin`

**Comment by supaht** [comment]
I'm having this issue as well after upgrading to high sierra. Were you able to find a solution?

**Comment by ttyson99** [comment]
Yes I simply put my github creds in the username and password fields:


[cid:image001.png@01D3703F.F59C7B40]


[Door IT Partners]<https://www.reddoorit.com/>Tony Tyson
CTO
Red Door IT Partners, Inc.
2201 Francisco Dr. #140-130, El Dorado Hills, CA 95762
M: +1 415 279 3610 | tony@reddoorit.com<mailto:tony@reddoorit.com>
