### ISSUE TITLE
Failed to connect to NodeJS - Max connection attempts reached

### ISSUE THREAD

**Issue by asnowfix** [zaggino/brackets-git#468]
Leaving Brackets alone for a few minutes produces this error. Later behavior does not seem to be affected. I have a couple (many?) of extensions installed. I am using the "proxy" configuration parameter (as I am behind a corporate HTTP & HTTPS proxy).

--------------------------------

*Brackets 0.38.0-12606 (win), Git 1.8.3.msysgit.0 & Brackets-Git 0.13.10*

**Failed to connect to NodeJS. If you&#39;ve just updated the extension then close all instances of Brackets and try starting again.**

```
Error: Max connection attempts reached
```

```
Error: Max connection attempts reached
    at Object.exports.toError (file:///C:/Users/kowalskif/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:158:16)
    at Object.<anonymous> (file:///C:/Users/kowalskif/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:67:37)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:550:26676)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:550:27489)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:550:28170)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:550:26676)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:550:27489)
    at Object.e.(anonymous function) [as reject] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty

**Comment by rakeshjuyal** [comment]
Same for me. As soon as I start Brackets it throws the same error "Unable to connect to NodeJS" . Max connection reached.

**Comment by byrnedo** [comment]
Getting this too on brackets installed 2 days ago. Pop up with 'Unable to connect to NodeJS...' as soon as it starts up

**Comment by tilwinjoy** [comment]
I just updated brackets to 1.7.0 on ubuntu 14.04 and started getting this error. I tried re-installing and restarting a couple of times but didn't help. When I downgraded to 1.6.0 it started working again.

I had no issues when I upgraded on windows 10. So there  seems to be an issue in ubuntu.

By the way, localhost is correctly mapped to `127.0.0.1`

**Comment by zaggino** [comment]
@abose @MarcelGerber @nethip did anything change specific for Linux with 1.7 ? See comment above please. I'll assume that https://github.com/zaggino/brackets-git/issues/1300 is also the same issue.

**Comment by nethip** [comment]
@zaggino We are currently looking at it. Once fixed we will refresh the installer builds.

**Comment by zaggino** [comment]
This is fixed in https://github.com/zaggino/brackets-electron/releases
