### ISSUE TITLE
Git Checkout failed

### ISSUE THREAD

**Issue by angtoko** [zaggino/brackets-git#865]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.8*

**Git Checkout failed**

```
Error: error: pathspec '.gitignore' did not match any file(s) known to git.
```

```
call: git checkout .gitignore
Error: error: pathspec '.gitignore' did not match any file(s) known to git.
    at Object.exports.toError (file:///C:/Users/Windows%C2%AE7/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/Windows%C2%AE7/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.10.
