### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by hiteshbal91** [zaggino/brackets-git#870]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.0.0-15191 (linux), Git 1.9.1 & Brackets-Git 0.14.9*

**Pushing to remote failed**

```
Error: error: object file .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 is empty
error: object file .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 is empty
fatal: loose object 8349c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 (stored in .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3) is corrupt
fatal: The remote end hung up unexpectedly
```

```
call: git push --porcelain --progress origin master
Error: error: object file .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 is empty
error: object file .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 is empty
fatal: loose object 8349c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3 (stored in .git/objects/83/49c5cfdb77430e8fd5e9df8cf72f09dbd3e2f3) is corrupt
fatal: The remote end hung up unexpectedly
    at Object.exports.toError (file:///home/hdb/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/hdb/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26676)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27489)
    at NodeConnection._receive (/utils/NodeConnection.js:494:34)
```

**Comment by zaggino** [comment]
http://stackoverflow.com/questions/11706215/how-to-fix-git-error-object-file-is-empty
