### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by phanect** [zaggino/brackets-git#871]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

1. `File` -> `Open Folder` a folder which contains git repo
2. Remove the folder
3. Following error is occured 

--------------------------------

*Brackets 1.1.0-15558 (linux), Git 2.1.0 & Brackets-Git 0.14.9*

**Refreshing gutter failed!**

```
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

```
call: git status -u --porcelain -- test/sequelize/option.js
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
    at Object.exports.toError (file:///home/phanect/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/phanect/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Why would you open a folder and then delete it?
What would you expect to happen, if not an error?

**Comment by phanect** [comment]
Sorry for too late reply... I may missed your reply.

> Why would you open a folder and then delete it?
Because I found the repo currently opening is no longer required while I was editing.

> What would you expect to happen, if not an error?
I thought no error should happen, or more appropriate error message (e.g. "Repo is not found") because current error message shows raw error stack trace.

However, now I'm not sure if those solutions are appropriate.
I close this issue for now. Please reopen if you think you need to change this.
