### ISSUE TITLE
Git Checkout failed

### ISSUE THREAD

**Issue by jccguimaraes** [zaggino/brackets-git#876]
selected multi files and then clicked in the button 'discard changes' on one of them

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Git Checkout failed**

```
Error: error: pathspec 'lib/directives/bf-settings-state-directive.js' did not match any file(s) known to git.
```

```
call: git checkout lib/directives/bf-settings-state-directive.js
Error: error: pathspec 'lib/directives/bf-settings-state-directive.js' did not match any file(s) known to git.
    at Object.exports.toError (file:///Users/joaoguimaraes/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/joaoguimaraes/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.10.
