### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by lasida** [zaggino/brackets-git#878]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (linux), Git 2.2.1 & Brackets-Git 0.14.9*

**Refreshing gutter failed!**

```
Error: error: bad index file sha1 signature
fatal: index file corrupt
```

```
call: git status -u --porcelain -- footer.php
Error: error: bad index file sha1 signature
fatal: index file corrupt
    at Object.exports.toError (file:///home/lasida/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/lasida/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
`index file corrupt`, tried cloning the repository again?
