### ISSUE TITLE
Failed push to Git-FTP remote.

### ISSUE THREAD

**Issue by fgjeremy** [zaggino/brackets-git#881]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Failed push to Git-FTP remote.**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp push --scope JUB-FTP
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///Users/jeremygunn/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/jeremygunn/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
You need to install it correctly like this:
https://github.com/git-ftp/git-ftp/blob/develop/INSTALL.md

**Comment by fgjeremy** [comment]
Strange, that’s how i installed it, and when i launch git from the command terminal using git ftp it allows me to run commands….


Do i have to install git-ftp per git repository?

**Comment by zaggino** [comment]
Nope, but you have to install it into a git directory which Brackets is using, you can check which one is it in Brackets Git settings dialog. Sometimes it happens that people on Mac have multiple Git installations installed. Common paths are `/usr/local/git/bin/git` and `/usr/bin/git`

**Comment by zaggino** [comment]
If you'll see only `git` in the settings dialog, use `which git` in terminal to see which one the extension is using. If it's installed correctly, command `git ftp --help` from terminal should launch without the message `git: 'ftp' is not a git command`
