### ISSUE TITLE
Getting remotes failed!

### ISSUE THREAD

**Issue by ehitze** [zaggino/brackets-git#882]
I get a Git extension error dialog when first opening Brackets.

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.8.5.2 (Apple Git-48) & Brackets-Git 0.14.9*

**Getting remotes failed!**

```
Error: fatal: Not a git repository (or any parent up to mount point /Volumes/002-Web)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

```
call: git remote -v
Error: fatal: Not a git repository (or any parent up to mount point /Volumes/002-Web)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    at Object.exports.toError (file:///Users/c101edh/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/c101edh/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
I was not able to replicate this issue, can you provide more detailed information?
