### ISSUE TITLE
Merge abort failed

### ISSUE THREAD

**Issue by gtarun** [zaggino/brackets-git#889]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 2.0.0 & Brackets-Git 0.14.9*

**Merge abort failed**

```
Error: warning: failed to remove protected/runtime/gii-1.1.15-dev/ModelCode.php
```

```
call: git clean -f -d
Error: warning: failed to remove protected/runtime/gii-1.1.15-dev/ModelCode.php
    at Object.exports.toError (file:///Users/Tarun/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/Tarun/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by gtarun** [comment]
Sometime when I get conflicts and fix them and then git merge all the files it removes all folder from local machine which are mentioned in .gitignore. 

I face this issue 4-5 times, So I think I should bring this into notice.

**Comment by zaggino** [comment]
Wasn't able to replicate this, `clean -f -d` which is mentioned here doesn't touch ignored files/folders.
Can you please provide a step by step scenario on how to replicate the problem?

**Comment by gtarun** [comment]
There are no special steps, 
1. working on a branch, switched branch 3-4 times and committed and pushed code 
2. when I pull there were many conflicts, when I resolved all and try to push it again, it pushed code but removed all the folders which are mentioned in the gitignore file as these should not be consider while pushing
