### ISSUE TITLE
Rebase failed

### ISSUE THREAD

**Issue by FezVrasta** [zaggino/brackets-git#890]
I was trying to update the `gh-pages` branch of my repository fetching from `master`

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 2.2.1 & Brackets-Git 0.14.9*

**Rebase failed**

```
Error: /usr/local/Cellar/git/2.2.1/libexec/git-core/git-rebase: line 47: git-sh-setup: No such file or directory
```

```
call: git rebase --ignore-date master
Error: /usr/local/Cellar/git/2.2.1/libexec/git-core/git-rebase: line 47: git-sh-setup: No such file or directory
    at Object.exports.toError (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/federicozivolo/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
see https://github.com/zaggino/brackets-git/issues/816
