### ISSUE TITLE
Failed push to Git-FTP remote.

### ISSUE THREAD

**Issue by ejallier** [zaggino/brackets-git#907]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Failed push to Git-FTP remote.**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp push --scope tester
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///Users/erwann/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/erwann/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git/blob/master/docs/GIT-FTP.md
