### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by rockts** [zaggino/brackets-git#908]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Pushing to remote failed**

```
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://rockts:***@github.com/rockts/php-c.git/'
```

```
call: git push --porcelain --progress --set-upstream php-c master
Error: remote: Invalid username or password.
fatal: Authentication failed for 'https://rockts:8363678@github.com/rockts/php-c.git/'
    at Object.exports.toError (file:///Users/rockts/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/rockts/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Error says `Invalid username or password.`
