### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by ryuken** [zaggino/brackets-git#910]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

I just left Brackets open. Maybe it has to do with waking from sleep?

--------------------------------

*Brackets 1.1.0-15558 (linux), Git 1.9.1 & Brackets-Git 0.14.10*

**Refreshing gutter failed!**

```
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

```
call: git status -u --porcelain -- modules/LVS/views/documents.html
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
    at Object.exports.toError (file:///home/macbook/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/macbook/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
@ryuken It's a Brackets problem, nothing I can do with it right now, see https://github.com/zaggino/brackets-git/issues/814
