### ISSUE TITLE
Rebase failed

### ISSUE THREAD

**Issue by andreaj8** [zaggino/brackets-git#943]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Rebase failed**

```
Error: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-rebase: line 45: git-sh-setup: No such file or directory
```

```
call: git rebase --ignore-date master
Error: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-rebase: line 45: git-sh-setup: No such file or directory
    at Object.exports.toError (file:///Users/jay/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///Users/jay/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
@andreaj8 see https://github.com/zaggino/brackets-git/issues/816
