### ISSUE TITLE
Creating new branch failed

### ISSUE THREAD

**Issue by Kem1980** [zaggino/brackets-git#954]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17*

**Creating new branch failed**

```
Error: fatal: 'new landing' is not a valid branch name.
```

```
call: git checkout -b new landing master
Error: fatal: 'new landing' is not a valid branch name.
    at Object.exports.toError (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
To fix: prevent users from entering invalid characters (space in this case) for branch names
