### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by Kem1980** [zaggino/brackets-git#956]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17*

```
Error: Terminal configuration invalid, restoring defaults. Restart Brackets to apply.
```

```
Error: Terminal configuration invalid, restoring defaults. Restart Brackets to apply.
    at file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:159:27
    at tryCatch1 (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (file:///C:/Users/or858_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2666:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///C:/

**Comment by zaggino** [comment]
To fix: this should be an unreportable `ExpectedError`
