### ISSUE TITLE
Remove scope failed

### ISSUE THREAD

**Issue by Galparsson98** [zaggino/brackets-git#970]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17*

**Remove scope failed**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp remove-scope https://github
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///C:/Users/FPE/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/FPE/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
git-ftp is not properly installed, see https://github.com/zaggino/brackets-git/blob/master/docs/GIT-FTP.md
