### ISSUE TITLE
brackets-git cannot open terminal

### ISSUE THREAD

**Issue by bariyu** [zaggino/brackets-git#982]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (mac), Git 1.9.5 (Apple Git-50.3) & Brackets-Git 0.14.19*

```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:434:498: execution error: Expected end of line but found identifier. (-2741): osascript "/Users/barankucukguzel/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/barankucukguzel/Desktop/repo/scorebeyond/dashboard/"
```

```
Error: Error: /Users/barankucukguzel/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:434:498: execution error: Expected end of line but found identifier. (-2741): osascript "/Users/barankucukguzel/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/barankucukguzel/Desktop/repo/scorebeyond/dashboard/"
    at file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/utils/Terminal.js:71:19
    at tryCatch1 (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_rejectPromises [as _rejectPromises] (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2658:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///Users/barankucukguzel/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by zaggino** [comment]
try installing http://iterm2.com/
