### ISSUE TITLE
Unexpected error in CLI handler - close all instances of Brackets and start again to reload

### ISSUE THREAD

**Issue by dvbondoy** [zaggino/brackets-git#983]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (linux) & Brackets-Git 0.14.19*

**Unexpected error in CLI handler - close all instances of Brackets and start again to reload**

```
TypeError: Cannot call method 'spawn' of undefined
```

```
TypeError: Cannot call method 'spawn' of undefined
    at file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:167:55
    at tryCatch1 (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4988:19)
    at Promise$_callHandler [as _callHandler] (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2333:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2349:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2521:14)
    at Promise$_fulfillPromises [as _fulfillPromises] (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:2666:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:157:12)
    at Async$consumeFunctionBuffer (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:120:14)
    at MutationObserver.Promise$_Scheduler (file:///home/jun/.config/Brackets/extensions/user/zaggino.brackets-git/thirdparty/bluebird.js:4260:17)
```

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git/search?q=Cannot+call+method+%27spawn%27+of+undefined&type=Issues&utf8=%E2%9C%93
