### ISSUE TITLE
Failed to get history

### ISSUE THREAD

**Issue by through-a-haze** [zaggino/brackets-git#984]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.4.msysgit.2 & Brackets-Git 0.14.19*

**Failed to get history**

```
Error: fatal: C:/Users/***/AppData/Local/Temp/fz3temp-1/style.css: 'C:/Users/Haze/AppData/Local/Temp/fz3temp-1/style.css' is outside repository
```

```
call: git log -100 --format=%h_._%H_._%an_._%ai_._%ae_._%s_._%b_.nw._ master -- C:/Users/Haze/AppData/Local/Temp/fz3temp-1/style.css
Error: fatal: C:/Users/Haze/AppData/Local/Temp/fz3temp-1/style.css: 'C:/Users/Haze/AppData/Local/Temp/fz3temp-1/style.css' is outside repository
    at Object.exports.toError (file:///C:/Users/Haze/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/Haze/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
need info how to replicate the issue

**Comment by through-a-haze** [comment]
Sorry, I can't reproduce the issue anymore. I think it may be closed.
