### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by N07070** [zaggino/brackets-git#988]
I setted a apache document root in the same directory as the git one.

--------------------------------

*Brackets 1.2.0-15697 (linux), Git 2.3.4 & Brackets-Git 0.14.19*

**Refreshing gutter failed!**

```
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

```
call: git status -u --porcelain -- model/php/variables.php
Error: Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
    at Object.exports.toError (file:///home/xxx/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///home/xxx/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
Improved error handling for this in `0.14.24`
