### ISSUE TITLE
Failed push to Git-FTP remote.

### ISSUE THREAD

**Issue by roomiand** [zaggino/brackets-git#993]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.2.msysgit.0 & Brackets-Git 0.14.22*

**Failed push to Git-FTP remote.**

```
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

```
call: git ftp push --scope peru
Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
    at Object.exports.toError (file:///C:/Users/Ronald%20Andrade/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/Ronald%20Andrade/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-git/blob/master/docs/GIT-FTP.md
