### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by RemeJuan** [zaggino/brackets-git#996]
Selected any file

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.23*

**Refreshing gutter failed!**

```
Error: fatal: unable to read tree d2202850f1ac0b7c1c4be58a3ece178883f68f09
```

```
call: git status -u --porcelain -- package.json
Error: fatal: unable to read tree d2202850f1ac0b7c1c4be58a3ece178883f68f09
    at Object.exports.toError (file:///C:/Users/Reme/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/Reme/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27724)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by zaggino** [comment]
your repository is probably corrupted, google `unable to read tree`

http://stackoverflow.com/questions/20870895/how-to-diagnose-and-fix-git-fatal-unable-to-read-tree
