### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by tebs1200** [zaggino/brackets-git#999]
I've encountered this issue a couple of times after committing a gherkin file:

 * I made changes to a gherkin file.
 * I saved the file
 * I selected the file to add it.
 * I clicked `Commit`
 * I provided the commit message
 * I clicked `Ok`
 * The error message popped up saying `Mode gherkin failed to advance stream.`.

It looks like the commit actually succeeds, but after that, the git plugin doesn't seem to recognise any saves as having modified the file. You need to restart Brackets before it will work again.

--------------------------------

*Brackets 1.2.0-15697 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.23*

**Refreshing gutter failed!**

```
Error: Mode gherkin failed to advance stream.
```

```
Error: Mode gherkin failed to advance stream.
    at readToken (/thirdparty/CodeMirror2/lib/codemirror.js:5972:11)
    at processLine (/thirdparty/CodeMirror2/lib/codemirror.js:6097:7)
    at eval (/thirdparty/CodeMirror2/lib/codemirror.js:1579:7)
    at Object.LeafChunk.iterN (/thirdparty/CodeMirror2/lib/codemirror.js:6444:13)
    at Object.BranchChunk.iterN (/thirdparty/CodeMirror2/lib/codemirror.js:6538:21)
    at BranchChunk.iterN (/thirdparty/CodeMirror2/lib/codemirror.js:6538:21)
    at createObj.iter (/thirdparty/CodeMirror2/lib/codemirror.js:6575:20)
    at getStateBefore (/thirdparty/CodeMirror2/lib/codemirror.js:1578:9)
    at getLineStyles (/thirdparty/CodeMirror2/lib/codemirror.js:6079:62)
    at buildLineContent (/thirdparty/CodeMirror2/lib/codemirror.js:6139:40)
```

**Comment by zaggino** [comment]
Seems like a `CodeMirror2` issue according to the stack. And also I've no idea what `gherkin` is :)

**Comment by tebs1200** [comment]
Apologies for the slow reply.

[Gherkin](https://cucumber.io/docs/reference) is the syntax that Behaviour Driven Development requirement specs are written in for Cucumber.

I don't know if this is still an issue as it's been a little while since I've used Brackets for Gherkin.

**Comment by zaggino** [comment]
Closing this, from the stack it's a CodeMirror error anyway.
